CREATE TABLE "bootcamp_test_sardi" (
	"region" TEXT NULL DEFAULT NULL,
	"country" TEXT NULL DEFAULT NULL,
	"state" TEXT NULL DEFAULT NULL,
	"city" TEXT NULL DEFAULT NULL,
	"month" INTEGER NULL DEFAULT NULL,
	"day" INTEGER NULL DEFAULT NULL,
	"year" INTEGER NULL DEFAULT NULL,
	"avgtemperature" NUMERIC NULL DEFAULT NULL
)
;
